### ISSUE TITLE
LRT Values and other concerns

### ISSUE THREAD

**Issue by rhshah** [zeeev/wham#9]
Hi Zev Kronenberg,

This a great tool, I got to know about this from Brad Chapman's post. 
I was testing WHAM and had some issues:
1. For the result I did not have LRT score for cases and controls mode, all LRT score's where 0. But it did pick up true positive event. 
2. NA: The number of reads that do support any type of structural variant . 
Here shouldn't the number of reads be for the specific event. I know you decide whether the event is Deletion, Inversion etc when you classify but this would really help in filtering ).
3. It would also help if you would put a little more explanation of the use of gene target bed file.
4. Also when its a translocation which was the true positive in my case. I saw it as being annotated as Deletion. Can you elaborate more on your classification strategy in the help section.

Thanks,
Ronak

**Comment by jewmanchue** [comment]
Thank you for using Wham and posting an issue. 

1. Can you post a few lines of the VCF where you see this problem?
2.  I will update the wording on the wiki.  It should state: the number of reads supporting the SV reported in the alt field.  For example if WHAM identifies the breakpoints of a deletion, it will be the number of reads supporting the current positions breakpoint.
3. I will do this in the next couple of days.
4. The classifier is the newest portion of code.  Brad also pointed out a similar issue.  What I have done is provided a new training dataset:  master/utils/WHAM_training_phase3_10bp_training.txt that may solve some of the classification issues.  



I would recommend checking out master rather than v1.7.0.  I'm in the process of tagging v1.8.0, but all the improvements are currently on master.

**Comment by rhshah** [comment]
Here is the output of the true positive events:

22	29688285	.	N	CTTTACGACATAATAAAAATAATGTAACTGACCAAATTGAGATGGAA	.	.	LRT=0;WAF=1e-06,1,0.500001;GC=1,1;AT=0,0,0,0,0.0597015,0,0.0358209,0.0537313,0.0179104,0.0179104,0.940299,0.0119403,0,0,0,0,0;SI=1.80377;PU=33;SU=18;CU=184;RD=335;NC=30;MQ=60;MQF=0;SP=sr;BE=8,145055127,18;DI=f;END=.;SVLEN=.;WC=DEL;WP=0.6,0.088,0.1376,0.1744	GT:GL:NR:NA:NS:RD	1/1:-255,-255,-0.000218:0:218:43:218	0/0:-0.000117,-255,-255:117:0:0:117
22	29688292	.	N	CTAAGCTACATGAAGCCCCACTTTATATTCTAACCTGAGCAC	.	.	LRT=0;WAF=1e-06,1,0.500001;GC=1,1;AT=0,0,0,0,0.0574713,0,0.0344828,0.0517241,0.0172414,0.0172414,0.942529,0.0114943,0,0,0,0,0;SI=1.91911;PU=10;SU=2;CU=185;RD=348;NC=6;MQ=60;MQF=0;SP=sr;BE=21,39775029,2;DI=b;END=.;SVLEN=.;WC=DEL;WP=0.612,0.088,0.1296,0.1704	GT:GL:NR:NA:NS:RD	1/1:-255,-255,-0.00023:0:230:43:230	0/0:-0.000118,-255,-255:118:0:0:118


As you see for both the LRT is given as 0. 

For the VCF file all entries have LRT=0.
-bash-4.1$ cat testWham.classify.vcf | grep "LRT=0"| wc -l
666
-bash-4.1$ cat testWham.classify.vcf | grep -v "^#" | wc -l
666

Sure I will probably wait for you to release the v1.8.0 and the try it again.

Thanks for your response.
